In [0]:
!pip install -U finance-datareader
import FinanceDataReader as fdr
df_krx = fdr.StockListing('KRX')

In [0]:
import pandas as pd
import numpy as np

In [0]:
#name=input('주식 코드 기업명 ?') #find 종목코드 및 정보
#df_krx[df_krx['Name'].str.contains(name)]

In [0]:
KOSPI = fdr.DataReader('KS11', '2015-01-01','2019-11-25')
SAMSUNG = fdr.DataReader('005930', '2015-01-01','2019-11-25')
KEPCO = fdr.DataReader('015760', '2015-01-01','2019-11-25')
SKtelecom = fdr.DataReader('017670', '2015-01-01','2019-11-25')
POSCO = fdr.DataReader('005490', '2015-01-01','2019-11-25')
HYUNDAI = fdr.DataReader('005380', '2015-01-01','2019-11-25')

In [0]:
JB = fdr.DataReader('052670', '2019-01-01','2019-12-04')
SJ = fdr.DataReader('001360', '2019-01-01','2019-12-04')
SP = fdr.DataReader('013810', '2019-01-01','2019-12-04')
BT = fdr.DataReader('065450', '2019-01-01','2019-12-04')
DI = fdr.DataReader('045390', '2019-01-01','2019-12-04')

In [0]:
df = pd.concat([KOSPI['Close'],SAMSUNG['Close'],KEPCO['Close'],SKtelecom['Close'],POSCO['Close'],HYUNDAI['Close']], axis=1)
df.set_axis(['KOSPI','SAMSUNG','KEPCO','SKtelecom','POSCO','HYUNDAI'],axis=1,inplace=True)
#df.columns = ['KOSPI','SAMSUNG','KEPCO','SKtelecom','POSCO','HYUNDAI']

In [0]:
df = pd.concat([JB['Close'],SJ['Close'],SP['Close'],BT['Close'],DI['Close']], axis=1)
df.set_axis(['JB','SJ','SP','BT','DI'],axis=1,inplace=True)

In [0]:
df.shape

(229, 5)

In [0]:
df.head(3)

JB    SJ    SP    BT    DI
Date                                    
2019-01-02  3755  2510  3885  2325  7770
2019-01-03  3670  2460  4000  2250  7910
2019-01-04  3650  2530  3970  2290  7770

In [0]:
df_rev = df.diff(axis=0 , periods=1)/df.shift(periods=1)
df_rev.dropna(inplace=True)

In [0]:
df_rev.shape

(228, 5)

In [0]:
import datetime

In [0]:
df_rev['day'] = df_rev.index.weekday_name
df_rev['year'] = df_rev.index.year
df_rev['month'] = df_rev.index.month

In [0]:
df_rev.head(3)

JB        SJ        SP  ...       day  year month
Date                                      ...                      
2019-01-03 -0.022636 -0.019920  0.029601  ...  Thursday  2019     1
2019-01-04 -0.005450  0.028455 -0.007500  ...    Friday  2019     1
2019-01-07  0.009589  0.007905  0.042821  ...    Monday  2019     1

[3 rows x 8 columns]

In [0]:
df_rev.tail(3)

JB        SJ        SP  ...        day  year month
Date                                      ...                       
2019-12-02  0.055829 -0.004926  0.017081  ...     Monday  2019    12
2019-12-03  0.045101 -0.012376 -0.013740  ...    Tuesday  2019    12
2019-12-04  0.041667 -0.003759  0.185759  ...  Wednesday  2019    12

[3 rows x 8 columns]

# 20191128

## 과업 5개의 주가 월별 수익률을 구하시오.

In [0]:
df_rev['month2'] = df_rev['year'].astype(str)+'_'+df_rev['month'].astype(str)

In [0]:
rev_m = df_rev.groupby(['month2']).mean().iloc[:,0:6]
rev_m.head()

JB        SJ        SP        BT        DI  year
month2                                                         
2019_1   0.017620  0.004092  0.013154  0.003249  0.004268  2019
2019_10  0.021585  0.021641 -0.003554  0.000739 -0.004972  2019
2019_11 -0.007662  0.001888  0.008727  0.005790 -0.004973  2019
2019_12  0.047532 -0.007021  0.063033  0.004887 -0.008100  2019
2019_2  -0.015714  0.000312 -0.010604  0.014825 -0.005889  2019

In [0]:
import matplotlib.pyplot as plt
plt.plot(rev_m.index, rev_m[['SAMSUNG','KEPCO','SKtelecom','POSCO','HYUNDAI']])
plt.legend(rev_m[['SAMSUNG','KEPCO','SKtelecom','POSCO','HYUNDAI']],bbox_to_anchor=(1,1))
plt.axhline(y=0, color='m')

plt.show()


## 삼성전자 요일별, 연도별 수익률 나무상자그림을 그리시오.

In [0]:
import matplotlib.pyplot as plt
import seaborn as sns

sns.boxplot(x='day', y='SAMSUNG', hue='year', data=df_rev)

plt.show()

In [0]:
import matplotlib.pyplot as plt
import seaborn as sns

sns.boxplot(x='day', y='KEPCO', hue='year', data=df_rev)

plt.show()

In [0]:
import matplotlib.pyplot as plt
import seaborn as sns

sns.boxplot(x='day', y='SKtelecom', hue='year', data=df_rev)

plt.show()

In [0]:
import matplotlib.pyplot as plt
import seaborn as sns

sns.boxplot(x='day', y='POSCO', hue='year', data=df_rev)

plt.show()

In [0]:
import matplotlib.pyplot as plt
import seaborn as sns

sns.boxplot(x='day', y='HYUNDAI', hue='year', data=df_rev)

plt.show()

#20191203

##과업 연도별 기업별 나무상자그림을 그리시오.

In [0]:
df_rev.head(2)

In [0]:
import matplotlib.pyplot as plt
import seaborn as sns

sns.boxplot(x='year', y='SAMSUNG', data=df_rev)

plt.show()

In [0]:
import matplotlib.pyplot as plt
import seaborn as sns

sns.boxplot(x='year', y='SAMSUNG', data=df_rev)
sns.boxplot(x='year', y='KEPCO', data=df_rev)
sns.boxplot(x='year', y='SKtelecom', data=df_rev)
sns.boxplot(x='year', y='POSCO', data=df_rev)
sns.boxplot(x='year', y='HYUNDAI', data=df_rev)

plt.show()

In [0]:
df_rev.boxplot(column='SAMSUNG', by='year')
df_rev.boxplot(column='KEPCO', by='year')
df_rev.boxplot(column='SKtelecom', by='year')
df_rev.boxplot(column='POSCO', by='year')
df_rev.boxplot(column='HYUNDAI', by='year')

plt.show()

##과업 기대수익률 최대 포토폴리오를 출력하시오. 만약에 수익률이 음수이면 없음이라고 출력하시오.

2015년 없음

2016년 p3

2017년 p2

2018년 없음

2019년 p2

## 연도별 기대수익, 분산, 공분산(수업)

In [0]:
p1 = np.array([0.2, 0.2, 0.2, 0.2, 0.2])
p2 = np.array([0.4, 0.1, 0.4, 0.1, 0.0])
p3 = np.array([0.1, 0.2, 0.1, 0.4, 0.2])

In [0]:
pf = np.array([[0.2, 0.2, 0.2, 0.2, 0.2],
              [0.4, 0.1, 0.4, 0.1, 0.0],
              [0.1, 0.2, 0.1, 0.4, 0.2]])

In [0]:
df_exp = df_rev.groupby(['year']).mean().iloc[:,1:6]
df_var = df_rev.groupby(['year']).var().iloc[:,1:6]
df_cov15 = df_rev.groupby(['year']).cov().iloc[1:6,1:6]
df_cov16 = df_rev.groupby(['year']).cov().iloc[8:13,1:6]
df_cov17 = df_rev.groupby(['year']).cov().iloc[15:20,1:6]
df_cov18 = df_rev.groupby(['year']).cov().iloc[22:27,1:6]
df_cov19 = df_rev.groupby(['year']).cov().iloc[29:34,1:6]

In [0]:
p_exp = pd.concat([(p1*df_exp).sum(axis=1),(p2*df_exp).sum(axis=1),(p3*df_exp).sum(axis=1)],axis=1)
p_exp.columns=['p1','p2','p3']
p_var = pd.concat([(p1*df_var).sum(axis=1),(p2*df_var).sum(axis=1),(p3*df_var).sum(axis=1)],axis=1)
p_var.columns=['p1','p2','p3']
p_cov = pd.concat([df_cov15,df_cov16,df_cov17,df_cov18,df_cov19],axis=0)

In [0]:
p_exp

In [0]:
p_var

In [0]:
p_cov.iloc[0:5,0:5]

In [0]:
ab = np.matmul(pf,np.array(p_cov.iloc[0:5,0:5]))
abc = np.matmul(ab,pf.T)
abc

##과업 포토폴리오를 다음과 같이 구성하였다.(선형대수로 모두 바꾸기)

In [0]:
import numpy as np

pf = np.array([[0.2, 0.2, 0.2, 0.2, 0.2],
              [0.6, 0.1, 0.1, 0.1, 0.1],
              [0.2, 0.2, 0.3, 0.3, 0.0]])

In [0]:
rev=np.array(df_rev.iloc[:,:5])

In [0]:
rev.shape

(228, 5)

###exp

In [0]:
one = np.array(np.repeat(1,rev.shape[0]))
one.shape

(228,)

In [0]:
exp = one.T@rev/rev.shape[0]

In [0]:
exp.shape

(5,)

In [0]:
pf@exp

array([0.00157764, 0.00280579, 0.00206285])

In [0]:
df_rev.cov().iloc[:5,:5]

JB        SJ        SP        BT        DI
JB  0.002796  0.000404  0.000224  0.000171  0.000024
SJ  0.000404  0.001578  0.000121 -0.000068  0.000103
SP  0.000224  0.000121  0.000782  0.000346  0.000402
BT  0.000171 -0.000068  0.000346  0.001545 -0.000463
DI  0.000024  0.000103  0.000402 -0.000463  0.001513

###df_var, df_cov

In [0]:
exp_repeat = np.tile(exp,(rev.shape[0],1))
exp_repeat.shape #(1205, 5)

(228, 5)

In [0]:
#공분산_행렬이용
#공분산 Cov(X,Y) = E[(x-mu_x)*(y-mu_y)] = E[A * B] 라 하자.
A = rev.T - exp_repeat.T # (5, 1205)
B = rev - exp_repeat # (1205, 5)
(A @ B) #(5, 5)
cov = (A @ B)/rev.shape[0]
cov

array([[ 2.78387683e-03,  4.02638437e-04,  2.22678120e-04,
         1.69832327e-04,  2.39506371e-05],
       [ 4.02638437e-04,  1.57124868e-03,  1.20701237e-04,
        -6.77663252e-05,  1.02839372e-04],
       [ 2.22678120e-04,  1.20701237e-04,  7.78460242e-04,
         3.44343150e-04,  4.00722476e-04],
       [ 1.69832327e-04, -6.77663252e-05,  3.44343150e-04,
         1.53808669e-03, -4.61047432e-04],
       [ 2.39506371e-05,  1.02839372e-04,  4.00722476e-04,
        -4.61047432e-04,  1.50621179e-03]])

In [0]:
pf[0]@cov@pf[0].T #p1의 분산

0.0004278267294212356

In [0]:
pf[1]@cov@pf[1].T #p2의 분산

0.0011632235233786752

In [0]:
pf[2]@cov@pf[2].T #p3의 분산

0.0005303405296352625

In [0]:
pf@cov@pf.T

array([[0.00042783, 0.00057421, 0.00043273],
       [0.00057421, 0.00116322, 0.00059389],
       [0.00043273, 0.00059389, 0.00053034]])

#20191205

## 투자 포토폴리오 

기대수익률

위험(분산, 공분산)

In [0]:
pf@exp

array([0.00157764, 0.00280579, 0.00206285])

In [0]:
pf@cov@pf.T

array([[0.00042783, 0.00057421, 0.00043273],
       [0.00057421, 0.00116322, 0.00059389],
       [0.00043273, 0.00059389, 0.00053034]])

##시나리오 분석

### 최소분산 포토폴리오

In [0]:
import numpy.linalg as la

In [0]:
la.inv(cov)

array([[ 381.28517069,  -92.36640973,  -97.2414446 ,  -18.24639627,
          20.52915752],
       [ -92.36640973,  671.00432951, -109.0942655 ,   65.61411794,
           4.76315168],
       [ -97.2414446 , -109.0942655 , 1990.92562567, -656.06672531,
        -721.50434   ],
       [ -18.24639627,   65.61411794, -656.06672531,  939.18052776,
         457.83518289],
       [  20.52915752,    4.76315168, -721.50434   ,  457.83518289,
         995.3614905 ]])

In [0]:
o1 = np.array(np.repeat(1,cov.shape[0]))

In [0]:
o1@cov

array([0.00360298, 0.00212966, 0.00186691, 0.00152345, 0.00157268])

In [0]:
P = (o1@cov)/(o1@cov@o1.T)

In [0]:
P

array([0.33686314, 0.19911438, 0.17454779, 0.14243602, 0.14703867])

In [0]:
P@exp.T

0.0020683936292770007